name: "Release a tag"
on:
  push:
    tags:
      - v*

  workflow_dispatch:

jobs:
  # build_test:
  #   name: Build App
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [14.x]
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - uses: actions/checkout@v2

  #     # - name: setup node
  #     #   uses: actions/setup-node@master
  #     #   with:
  #     #     node-version: ${{ matrix.node-version }}

  #     # install applicaion dependencies
  #     # - name: Install dependencies
  #     #   run: |
  #     #     npm install
  #     #     npm ci 
  #     # # build the apps     
  #     # # - name: build
  #     # #   run: |
  #     # #     npm run build

  push_to_Docker_Hub:
    name: Push Images to DockerHub
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # build docker image and push to docker hub
    # only if the app build and test successfully
    # needs: [build_test]

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      # - name: Branch name
      #   id: branch_name
      #   run: |
      #     echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
      #     echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
      #     echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
    
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/whoami-no-cors:0.1.1
        
      - name: Run the image in a container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/whoami-no-cors:0.1.1
          run: |
            echo "runing the docker image"
            echo "Testing the nodejs  app endpoints"
            echo ${{ steps.docker_build.outputs.digest }}